name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Normalize variables to lowercase
        id: vars
        run: |
          echo "OWNER=${{ github.repository_owner }}" >> $GITHUB_ENV # Convert owner to lowercase
          echo "TAG=${{ github.ref_name }}" >> $GITHUB_ENV # Convert tag to lowercase

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ env.OWNER }}/s3-mirror:${{ env.TAG }}
            ghcr.io/${{ env.OWNER }}/s3-mirror:latest